"""add_traffic_limit_to_admin

Revision ID: 51eff4ccad55
Revises: 92315c762482
Create Date: 2025-08-10 00:58:14.958189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51eff4ccad55'
down_revision = '92315c762482'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admins', sa.Column('traffic_limit', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admins', 'traffic_limit')
    # ### end Alembic commands ###
